### ISSUE TITLE
Excellent job with your CSS code formatting and layout!

### ISSUE THREAD

**Issue by josephtkim** [kdotsee/teacozy#5]
Your CSS code looks great and appears to follow good formatting. 

A few suggestions for the CSS would be to add a space between the selector name and the opening curly brace, like so

```css
body {
}

header {
}
```

In addition, it would be a good idea to add descriptions above each section and to group the selectors according to the layout of the page. It can look something like

```css
/* Contact Section */
.contact {
  flex-direction: column;
  justify-content: center;
  font-family: Helvetica;
  text-align: center;
  color: seashell;
  height: 200px;
}

/* Footer Section */
footer {
  font-family: Helvetica;
  color: seashell;
  text-align: left;
  margin-left: 20px;
}
```
